### ISSUE TITLE
Question: Why are you using `nn.parameter.Parameter` with `requires_grad=False` instead of `register_buffer`?

### ISSUE THREAD

**Issue by kabouzeid** [jmclong/random-fourier-features-pytorch#6]
I'm not sure I understand what's going on, but why is this not a buffer (`register_buffer`)?

https://github.com/jmclong/random-fourier-features-pytorch/blob/d45556ab984ab675195c342b4f79675539292e0e/rff/layers.py#L36

**Comment by jmclong** [comment]
Hi Karim,

Thank you for reporting this issue.

I think that you are right, after reading the doc for `register_buffer`.

Did you encounter this issue when saving/restoring the model? I can add at test to check for this case.

Thanks,
Joshua

**Comment by jmclong** [comment]
Here's some similar issue:
https://github.com/typoverflow/UtilsRL/issues/11

**Comment by jmclong** [comment]
@kabouzeid,

Can you check to see if my recent changes in addressed this issue? Thanks!

**Comment by kabouzeid** [comment]
Thanks for addressing this so quickly! I haven't even tried the previous implementation. The previous implementation would have caused problems when eg locally freezing parts of the model using `.requires_grad_(false)` and later unfreeze using `.requires_grad_(true)`. This would have made `b` trainable by accident.

**Comment by jmclong** [comment]
Thank you for the explanation!

I'll add a test case for that and cut a new release.

Thanks.
